name: ProgressDialog Library Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
#   Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      if: (${{ github.event_name == 'push' }} && startsWith(github.ref, 'refs/tags/v')) || (${{ github.event_name == 'pull_request' }} && ${{ github.actor != 'dependabot[bot]' }})
      run: ./gradlew progressdialoglibrary:build progressdialoglibrary:publishToMavenLocal
