name: Create and Publish Release

on:
  workflow_run:
    workflows: ["ProgressDialog Library Build"]
    types:
      - completed
#   Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  createAndPublishRelease:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1.10.0
    - name: Create and Publish Release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
