name: Generate Docs and Deploy to GH Pages

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3.2.0
        with:
          java-version: 11
          distribution: adopt
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate KDoc
        if: ${{github.event_name == 'release'}}
        run: ./gradlew dokkaHtml
      - name: Generate JavaDoc
        if: ${{github.event_name == 'release'}}
        run: ./gradlew dokkaJavadoc
      - name: Deploy KDoc to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: progressdialoglibrary/build/dokka/html
          target-folder: kotlin/${{ github.event.release.tag_name }}/
      - name: Deploy JavaDoc to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: progressdialoglibrary/build/dokka/javadoc
          target-folder: java/${{ github.event.release.tag_name }}/  
      - name: Copy Logo File to KDoc Action
        uses: GuillaumeFalourd/copy-push-files@v1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          remote_repository: https://github.com/techinessoverloaded/progress-dialog
          target_branch: gh-pages
          target_dir: kotlin//${{ github.event.release.tag_name }}/images/
          source_files: assets/images/logo-icon.svg
      - name: Copy Logo File to JavaDoc Action
        uses: GuillaumeFalourd/copy-push-files@v1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          remote_repository: https://github.com/techinessoverloaded/progress-dialog
          target_branch: gh-pages
          target_dir: java//${{ github.event.release.tag_name }}/images/
          source_files: assets/images/logo-icon.svg    
